apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Chart.Name}}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf3
      app.kubernetes.io/instance: {{.Release.Name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iperf3
        app.kubernetes.io/instance: {{.Release.Name}}
    spec:
      containers:
        - name: iperf3
          image: {{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag }}
          command:
            - iperf3
            - -s
            - -p 5201
            - -i 1
            - --forceflush
            {{- if .Values.verbose }}
            - -V
            {{- end }}
          resources: {{ .Values.resources }}
          ports:
            - name: iperf3
              containerPort: 5201
              protocol: TCP
      restartPolicy: Always
status: {}
