{{- if .Values.service.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: iperf3_client
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIp -}}
  externalIPs:
    - {{.Values.service.externalIp}}
{{- end }}
  selector:
    app.kubernetes.io/name: iperf3_client
    app.kubernetes.io/instance: {{.Release.Name}}
  ports:
    - protocol: TCP
      port: {{.Values.service.port}}
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
{{- end }}
